#!/bin/bash

echo "🔍 Render Deployment Monitor"
echo "============================"
echo ""
echo "📝 Pre-deployment checklist:"
echo "✅ Pages directory removed (was causing Html import error)"
echo "✅ render.yaml updated to use pnpm"
echo "✅ Local build successful"
echo ""
echo "🚀 Push to trigger deployment:"
echo "   git push origin main"
echo ""
echo "📊 What to monitor on Render dashboard:"
echo ""
echo "1. Build Phase:"
echo "   - Should use Node 22 (from .nvmrc)"
echo "   - Should run: pnpm install --frozen-lockfile"
echo "   - Should run: pnpm run build"
echo "   - Look for: '✓ Generating static pages (9/9)'"
echo ""
echo "2. Common issues to watch for:"
echo "   ❌ 'Html should not be imported' - FIXED (removed pages dir)"
echo "   ❌ 'Module not found' - Check dependencies"
echo "   ❌ 'ENOENT' errors - File path issues"
echo ""
echo "3. Success indicators:"
echo "   ✅ 'Build succeeded'"
echo "   ✅ 'Service is live'"
echo "   ✅ Health check passing at /api/health"
echo ""
echo "📱 After deployment succeeds:"
echo "   - Test auth flow"
echo "   - Check console for errors"
echo "   - Verify MCP integration"
echo ""
echo "💡 Debug tips:"
echo "   - Check Render logs: https://dashboard.render.com"
echo "   - Use browser DevTools Network tab"
echo "   - Monitor /api/health endpoint"
