#!/bin/bash

# Setup script for creating Claude test user in AWS Cognito
# Run this to create the claude@test.siam.ai user in your Cognito User Pool

echo "🤖 AWS Cognito User Setup for Claude Test Account"
echo "=================================================="
echo ""

# Configuration
USER_POOL_ID="us-east-2_A0veaJRLo"
REGION="us-east-2"
EMAIL="claude@test.siam.ai"
USERNAME="claude-test"
TEMP_PASSWORD="Claude123!@#"

echo "User Pool ID: $USER_POOL_ID"
echo "Region: $REGION"
echo "Email: $EMAIL"
echo "Username: $USERNAME"
echo ""

# Check if AWS CLI is installed
if ! command -v aws &> /dev/null; then
    echo "❌ AWS CLI is not installed. Please install it first:"
    echo "   brew install awscli"
    echo "   or"
    echo "   pip install awscli"
    exit 1
fi

echo "📋 Option 1: Create user with temporary password (recommended)"
echo "=============================================================="
echo "Run this command to create the user:"
echo ""
echo "aws cognito-idp admin-create-user \\"
echo "  --user-pool-id $USER_POOL_ID \\"
echo "  --username $EMAIL \\"
echo "  --user-attributes Name=email,Value=$EMAIL Name=email_verified,Value=true \\"
echo "  --message-action SUPPRESS \\"
echo "  --temporary-password '$TEMP_PASSWORD' \\"
echo "  --region $REGION"
echo ""

echo "📋 Option 2: Create user and set permanent password"
echo "===================================================="
echo "Step 1 - Create the user:"
echo ""
echo "aws cognito-idp admin-create-user \\"
echo "  --user-pool-id $USER_POOL_ID \\"
echo "  --username $EMAIL \\"
echo "  --user-attributes Name=email,Value=$EMAIL Name=email_verified,Value=true \\"
echo "  --message-action SUPPRESS \\"
echo "  --region $REGION"
echo ""
echo "Step 2 - Set permanent password:"
echo ""
echo "aws cognito-idp admin-set-user-password \\"
echo "  --user-pool-id $USER_POOL_ID \\"
echo "  --username $EMAIL \\"
echo "  --password 'YourSecurePassword123!' \\"
echo "  --permanent \\"
echo "  --region $REGION"
echo ""

echo "📋 Option 3: Using AWS Console (Manual)"
echo "========================================"
echo "1. Go to: https://console.aws.amazon.com/cognito/home?region=$REGION"
echo "2. Click on User Pools"
echo "3. Select pool: $USER_POOL_ID"
echo "4. Go to 'Users' tab"
echo "5. Click 'Create user'"
echo "6. Enter:"
echo "   - Username: $EMAIL"
echo "   - Email: $EMAIL"
echo "   - Check 'Mark email as verified'"
echo "   - Set a temporary password"
echo "7. Click 'Create user'"
echo ""

echo "📋 Option 4: Sign up through the app (if enabled)"
echo "================================================="
echo "If self-registration is enabled, you can:"
echo "1. Go to https://thebetabase.com"
echo "2. Click 'Sign Up' (if available)"
echo "3. Enter email: $EMAIL"
echo "4. Complete the signup flow"
echo ""

echo "⚠️  Important Notes:"
echo "===================="
echo "1. The Railway deployment needs to complete for the updated allowed emails"
echo "2. Current deployment shows the old allowed list"
echo "3. Wait for deployment to finish, then the new email will be allowed"
echo "4. Check deployment status at: https://railway.com/project/12573897-7569-4887-89fa-55843ac7fab2"
echo ""

echo "📧 Since claude@test.siam.ai is not a real email:"
echo "=================================================="
echo "- Magic link emails won't be delivered"
echo "- Use password authentication instead"
echo "- Or implement a bypass for testing"
echo ""

echo "🔐 To test authentication after user creation:"
echo "=============================================="
echo "aws cognito-idp admin-initiate-auth \\"
echo "  --user-pool-id $USER_POOL_ID \\"
echo "  --client-id 5c6ll37299p351to549lkg3o0d \\"
echo "  --auth-flow ADMIN_NO_SRP_AUTH \\"
echo "  --auth-parameters USERNAME=$EMAIL,PASSWORD='YourPassword' \\"
echo "  --region $REGION"
echo ""

echo "✅ Once the user is created and deployment is complete:"
echo "========================================================"
echo "You'll be able to authenticate at https://thebetabase.com"
echo "with the claude@test.siam.ai email address!"