"use client";

import React, { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "../ui/card";
import { Badge } from "../ui/badge";
import { Button } from "../ui/button";
import { Textarea } from "../ui/textarea";
import { Label } from "../ui/label";
import { ScrollArea } from "../ui/scroll-area";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "../ui/select";
import {
  Brain,
  Sparkles,
  FileText,
  Code,
  Wand2,
  Copy,
  Download,
  Play,
  Settings,
  MessageSquare,
  FileCode,
  Zap,
  CheckCircle,
  AlertCircle,
} from "lucide-react";
import { cn } from "../../lib/utils";

interface GeneratedTest {
  id: string;
  name: string;
  type: string;
  language: string;
  code: string;
  description: string;
  coverage: string[];
  timestamp: Date;
}

export const AITestGenerator: React.FC = () => {
  const [prompt, setPrompt] = useState("");
  const [testType, setTestType] = useState("unit");
  const [language, setLanguage] = useState("typescript");
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedTests, setGeneratedTests] = useState<GeneratedTest[]>([
    {
      id: "1",
      name: "Authentication Flow Test",
      type: "e2e",
      language: "typescript",
      description:
        "Comprehensive test for user authentication including login, logout, and session management",
      coverage: ["Login", "Logout", "Session Persistence", "Error Handling"],
      timestamp: new Date(),
      code: `import { test, expect } from '@playwright/test';

test.describe('Authentication Flow', () => {
  test('should successfully authenticate with valid credentials', async ({ page }) => {
    // Navigate to login page
    await page.goto('/login');
    
    // Fill in credentials
    await page.fill('[data-testid="email-input"]', 'user@example.com');
    await page.fill('[data-testid="password-input"]', 'SecurePassword123');
    
    // Submit form
    await page.click('[data-testid="login-button"]');
    
    // Wait for navigation
    await page.waitForURL('/dashboard');
    
    // Verify successful login
    await expect(page.locator('[data-testid="user-avatar"]')).toBeVisible();
    await expect(page.locator('text=Welcome back')).toBeVisible();
  });

  test('should handle invalid credentials gracefully', async ({ page }) => {
    await page.goto('/login');
    
    await page.fill('[data-testid="email-input"]', 'invalid@example.com');
    await page.fill('[data-testid="password-input"]', 'WrongPassword');
    
    await page.click('[data-testid="login-button"]');
    
    // Check for error message
    await expect(page.locator('[data-testid="error-message"]')).toContainText('Invalid credentials');
    
    // Ensure we stay on login page
    await expect(page).toHaveURL('/login');
  });
});`,
    },
    {
      id: "2",
      name: "API Response Validation",
      type: "integration",
      language: "typescript",
      description: "Test API endpoints for correct response structure and error handling",
      coverage: ["API Response", "Error Codes", "Data Validation"],
      timestamp: new Date(),
      code: `import { describe, it, expect } from 'vitest';
import { apiClient } from '../src/lib/api';

describe('API Integration Tests', () => {
  it('should fetch user data successfully', async () => {
    const response = await apiClient.get('/api/user/profile');
    
    expect(response.status).toBe(200);
    expect(response.data).toHaveProperty('id');
    expect(response.data).toHaveProperty('email');
    expect(response.data).toHaveProperty('name');
  });

  it('should handle 404 errors appropriately', async () => {
    try {
      await apiClient.get('/api/nonexistent');
    } catch (error) {
      expect(error.response.status).toBe(404);
      expect(error.response.data).toHaveProperty('message');
    }
  });
});`,
    },
  ]);

  const [selectedTest, setSelectedTest] = useState<GeneratedTest | null>(generatedTests[0]);

  const handleGenerate = async () => {
    setIsGenerating(true);

    // Simulate AI generation
    setTimeout(() => {
      const newTest: GeneratedTest = {
        id: Date.now().toString(),
        name: "Generated Test Suite",
        type: testType,
        language: language,
        description: `AI-generated ${testType} test based on: ${prompt}`,
        coverage: ["Component Rendering", "User Interactions", "State Management"],
        timestamp: new Date(),
        code: `// AI-Generated Test
import { test, expect } from '@playwright/test';

test.describe('${prompt}', () => {
  test('should ${prompt.toLowerCase()}', async ({ page }) => {
    // AI-generated test implementation
    await page.goto('/');
    
    // Test logic based on natural language prompt
    // This would be generated by the AI model
    
    await expect(page).toHaveTitle(/SIAM/);
  });
});`,
      };

      setGeneratedTests([newTest, ...generatedTests]);
      setSelectedTest(newTest);
      setIsGenerating(false);
      setPrompt("");
    }, 2000);
  };

  const testTypeOptions = [
    { value: "unit", label: "Unit Test", icon: <Code className="h-4 w-4" /> },
    {
      value: "integration",
      label: "Integration Test",
      icon: <Zap className="h-4 w-4" />,
    },
    {
      value: "e2e",
      label: "End-to-End Test",
      icon: <FileCode className="h-4 w-4" />,
    },
    {
      value: "performance",
      label: "Performance Test",
      icon: <Settings className="h-4 w-4" />,
    },
  ];

  const promptSuggestions = [
    "Test user authentication flow with magic links",
    "Verify file upload functionality works correctly",
    "Test real-time chat message streaming",
    "Validate API error handling and retry logic",
    "Test responsive design on mobile devices",
    "Verify accessibility compliance for screen readers",
  ];

  return (
    <div className="grid grid-cols-12 gap-6">
      {/* Generation Panel */}
      <div className="col-span-5 space-y-4">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Brain className="h-5 w-5 text-primary" />
              AI Test Generator
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {/* Natural Language Input */}
            <div className="space-y-2">
              <Label htmlFor="prompt">Describe what you want to test</Label>
              <Textarea
                id="prompt"
                placeholder="E.g., Test that users can successfully upload and process PDF documents..."
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                className="min-h-[100px]"
              />
            </div>

            {/* Quick Suggestions */}
            <div className="space-y-2">
              <Label>Quick Suggestions</Label>
              <div className="flex flex-wrap gap-2">
                {promptSuggestions.map((suggestion, index) => (
                  <Badge
                    key={index}
                    variant="outline"
                    className="cursor-pointer hover:bg-primary/10"
                    onClick={() => setPrompt(suggestion)}
                  >
                    {suggestion}
                  </Badge>
                ))}
              </div>
            </div>

            {/* Test Type Selection */}
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="test-type">Test Type</Label>
                <Select value={testType} onValueChange={setTestType}>
                  <SelectTrigger id="test-type">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {testTypeOptions.map((option) => (
                      <SelectItem key={option.value} value={option.value}>
                        <div className="flex items-center gap-2">
                          {option.icon}
                          <span>{option.label}</span>
                        </div>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <Label htmlFor="language">Language</Label>
                <Select value={language} onValueChange={setLanguage}>
                  <SelectTrigger id="language">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="typescript">TypeScript</SelectItem>
                    <SelectItem value="javascript">JavaScript</SelectItem>
                    <SelectItem value="python">Python</SelectItem>
                    <SelectItem value="java">Java</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            {/* Advanced Options */}
            <Card className="mac-card bg-muted/50">
              <CardContent className="p-4 space-y-3">
                <h4 c className="mac-title" lassName="mac-title text-sm font-medium">
                  Advanced Options
                </h4>
                <div className="space-y-2 text-sm">
                  <label className="flex items-center gap-2">
                    <input type="checkbox" className="rounded" defaultChecked />
                    Include assertions
                  </label>
                  <label className="flex items-center gap-2">
                    <input type="checkbox" className="rounded" defaultChecked />
                    Add error handling
                  </label>
                  <label className="flex items-center gap-2">
                    <input type="checkbox" className="rounded" />
                    Generate test data
                  </label>
                  <label className="flex items-center gap-2">
                    <input type="checkbox" className="rounded" />
                    Include performance metrics
                  </label>
                </div>
              </CardContent>
            </Card>

            {/* Generate Button */}
            <Button
              className="w-full mac-button mac-button-primary"
              size="lg"
              onClick={handleGenerate}
              disabled={!prompt || isGenerating}
            >
              {isGenerating ? (
                <>
                  <Sparkles className="h-4 w-4 mr-2 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Wand2 className="h-4 w-4 mr-2" />
                  Generate Test
                </>
              )}
            </Button>
          </CardContent>
        </Card>

        {/* Generated Tests History */}
        <Card>
          <CardHeader>
            <CardTitle className="text-lg">Generated Tests</CardTitle>
          </CardHeader>
          <CardContent className="p-0">
            <ScrollArea className="h-[200px]">
              <div className="p-4 space-y-2">
                {generatedTests.map((test) => (
                  <Card
                    key={test.id}
                    className={cn(
                      "mac-card",
                      "cursor-pointer transition-all hover:shadow-md",
                      selectedTest?.id === test.id && "ring-2 ring-primary"
                    )}
                    onClick={() => setSelectedTest(test)}
                  >
                    <CardContent className="p-4">
                      <div className="flex items-center justify-between mb-2">
                        <span className="font-medium text-sm">{test.name}</span>
                        <Badge variant="outline" className="text-xs">
                          {test.type}
                        </Badge>
                      </div>
                      <p className="text-xs text-muted-foreground truncate">{test.description}</p>
                    </CardContent>
                  </Card>
                ))}
              </div>
            </ScrollArea>
          </CardContent>
        </Card>
      </div>

      {/* Generated Test Preview */}
      <div className="col-span-7">
        {selectedTest ? (
          <Card className="mac-card h-full">
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle className="text-lg">{selectedTest.name}</CardTitle>
                  <p className="text-sm text-muted-foreground mt-2">{selectedTest.description}</p>
                </div>
                <div className="flex gap-2">
                  <Button className="mac-button mac-button-outline" variant="outline" size="sm">
                    <Copy className="h-4 w-4 mr-2" />
                    Copy
                  </Button>
                  <Button className="mac-button mac-button-outline" variant="outline" size="sm">
                    <Download className="h-4 w-4 mr-2" />
                    Export
                  </Button>
                  <Button className="mac-button mac-button-primary" size="sm">
                    <Play className="h-4 w-4 mr-2" />
                    Run Test
                  </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <Tabs defaultValue="code" className="h-full">
                <TabsList className="grid w-full grid-cols-3">
                  <TabsTrigger value="code">Generated Code</TabsTrigger>
                  <TabsTrigger value="coverage">Coverage Analysis</TabsTrigger>
                  <TabsTrigger value="suggestions">AI Suggestions</TabsTrigger>
                </TabsList>

                <TabsContent value="code" className="h-full">
                  <Card className="mac-card bg-muted/50">
                    <CardContent className="p-4">
                      <pre className="text-sm font-mono overflow-x-auto">
                        <code>{selectedTest.code}</code>
                      </pre>
                    </CardContent>
                  </Card>
                </TabsContent>

                <TabsContent value="coverage" className="space-y-4">
                  <Card>
                    <CardHeader>
                      <CardTitle className="text-base">Test Coverage Areas</CardTitle>
                    </CardHeader>
                    <CardContent>
                      <div className="space-y-2">
                        {selectedTest.coverage.map((area, index) => (
                          <div key={index} className="flex items-center gap-2">
                            <CheckCircle className="h-4 w-4 text-green-500" />
                            <span className="text-sm">{area}</span>
                          </div>
                        ))}
                      </div>
                    </CardContent>
                  </Card>

                  <Card>
                    <CardHeader>
                      <CardTitle className="text-base">Potential Gaps</CardTitle>
                    </CardHeader>
                    <CardContent>
                      <div className="space-y-2">
                        <div className="flex items-center gap-2">
                          <AlertCircle className="h-4 w-4 text-yellow-500" />
                          <span className="text-sm">Edge case: Empty input handling</span>
                        </div>
                        <div className="flex items-center gap-2">
                          <AlertCircle className="h-4 w-4 text-yellow-500" />
                          <span className="text-sm">Network timeout scenarios</span>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                </TabsContent>

                <TabsContent value="suggestions" className="space-y-4">
                  <Card className="mac-card bg-blue-500/10 border-blue-500/20">
                    <CardContent className="p-4">
                      <h3
                        c
                        className="mac-title"
                        lassName="mac-title font-medium mb-2 flex items-center gap-2"
                      >
                        <Sparkles className="h-4 w-4 text-blue-500" />
                        AI Recommendations
                      </h3>
                      <ul className="space-y-2 text-sm">
                        <li>• Consider adding retry logic for flaky network requests</li>
                        <li>• Add data-testid attributes to improve test stability</li>
                        <li>• Include accessibility checks using axe-core</li>
                        <li>• Add visual regression tests for UI components</li>
                      </ul>
                    </CardContent>
                  </Card>

                  <Card>
                    <CardHeader>
                      <CardTitle className="text-base">Related Tests to Generate</CardTitle>
                    </CardHeader>
                    <CardContent>
                      <div className="space-y-2">
                        <Button
                          variant="outline"
                          className="w-full justify-start mac-button mac-button-outline"
                          size="sm"
                        >
                          <MessageSquare className="h-4 w-4 mr-2" />
                          Test error boundary behavior
                        </Button>
                        <Button
                          variant="outline"
                          className="w-full justify-start mac-button mac-button-outline"
                          size="sm"
                        >
                          <FileText className="h-4 w-4 mr-2" />
                          Test data persistence
                        </Button>
                        <Button
                          variant="outline"
                          className="w-full justify-start mac-button mac-button-outline"
                          size="sm"
                        >
                          <Settings className="h-4 w-4 mr-2" />
                          Test configuration changes
                        </Button>
                      </div>
                    </CardContent>
                  </Card>
                </TabsContent>
              </Tabs>
            </CardContent>
          </Card>
        ) : (
          <Card className="mac-card h-full">
            <CardContent className="flex items-center justify-center h-full text-muted-foreground">
              Generate a test or select from history to preview
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
};

export default AITestGenerator;
