export const SupportConstants = {
  contacts: [
    {
      email: 'rick.barry@asburymedia.com',
      name: 'Rick Barry (Asbury Media)',
      phone: '+1 732 948 1413',
      isChecked: false,
    },
    {
      email: 'colie.brice@asburymedia.com',
      name: 'Colie Brice (Asbury Media)',
      phone: '+1 732 321 2751',
      isChecked: false,
    },
    {
      email: 'manuela.brice@asburymedia.com',
      name: 'Manuela Brice (Asbury Media)',
      phone: '+1 732 321 2751',
      isChecked: false,
    },
    {
      email: 'apptester03@asburymedia.com',
      name: 'Fiona Burgess (Asbury Media)',
      phone: '+353 87 395 9392',
      isChecked: false,
    },
    {
      email: 'ralph.capasso@sonymusic.com',
      name: 'Ralph Capasso (Sony Music)',
      phone: '+1 917 885 2714',
      isChecked: false,
    },
    {
      email: 'matt@mattcarpenter.com',
      name: 'Matt Carpenter (Asbury Media)',
      phone: '+353 87 982 7211',
      isChecked: false,
    },
    {
      email: 'arnab.ghosh.wipro@sonymusic.com',
      name: 'Arnab Ghosh (Sony Music)',
      phone: '+1 917 822 7217',
      isChecked: false,
    },
    {
      email: 'vamsikrishna.Gollapudi.infotech@sonymusic.com',
      name: 'Vamsi Gollapudi (Infotech)',
      phone: '+1 917 972 5747',
      isChecked: false,
    },
    {
      email: 'garima.gupta.infotechlimited@sonymusic.com',
      name: 'Garima Gupta (Infotech)',
      phone: '+1 973 767 6977',
      isChecked: false,
    },
    {
      email: 'prasad.inamdar.infotechlimited@sonymusic.com',
      name: 'Prasad Inamdar (Infotech)',
      phone: '+1 302 740 7475',
      isChecked: false,
    },
    {
      email: 'Nathaniel.Lovett@sonymusic.com',
      name: 'Nat Lovett (Sony Music)',
      phone: '+1 646 491 1590',
      isChecked: false,
    },
    {
      email: 'keith.mccarthy@asburymedia.com',
      name: 'Keith McCarthy (Asbury Media)',
      phone: '+1 609 290 2372',
      isChecked: false,
    },
    {
      email: 'jack.pitzer@asburymedia.com',
      name: 'Jack Pitzer (Asbury Media)',
      phone: '+1 201 218 4064',
      isChecked: false,
    },
    {
      email: 'Rohit.Raj.AsburyMedia@sonymusic.com',
      name: 'Rohit Raj (Asbury Media)',
      phone: '+1 201 925 1748',
      isChecked: false,
    },
    {
      email: 'abhishek.ray.infotechlimited@sonymusic.com',
      name: 'Abhishek Ray (Wipro)',
      phone: '+1 651 675 9610',
      isChecked: false,
    },
    {
      email: 'tom.ruff@asburymedia.com',
      name: 'Tom Ruff (Asbury Media)',
      phone: '+1 732 403 7251',
      isChecked: false,
    },
    {
      email: 'Christian.Seitz@sonymusic.com',
      name: 'Christian Seitz (Sony Music)',
      phone: '+1 646 932 2732',
      isChecked: false,
    },
    {
      email: 'shahenaaz.syed.imcassociates@sonymusic.com',
      name: 'Shahenaaz Syed (IMC Associates)',
      phone: '+1 732 986 6466',
      isChecked: false,
    },
    {
      email: 'David.Wenger@sonymusic.com',
      name: 'Dave Wenger (Sony Music)',
      phone: '+1 718 208 9290',
      isChecked: false,
    },
    {
      email: 'erik.wood@asburymedia.com',
      name: 'Erik Wood (Asbury Media)',
      phone: '+1 718 314 7113',
      isChecked: false,
    },
  ],
};
