"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import { cn } from "../../../lib/utils";
import { Button } from "../../ui/button";
import { Badge } from "../../ui/badge";
import {
  GitBranch,
  Workflow,
  Network,
  Loader2,
  X,
  Maximize2,
  Download,
  ZoomIn,
  ZoomOut,
  ChevronUp,
  Presentation,
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

type DiagramType = "workflow" | "explainer";

interface DiagramOfferProps {
  responseContent: string;
  onAccept?: () => void;
  onDismiss?: () => void;
  className?: string;
  autoGenerateDelay?: number; // ms to wait before showing offer (not generating)
}

interface DiagramState {
  status: "idle" | "generating" | "ready" | "error";
  imageBase64?: string;
  imageMimeType?: string;
  error?: string;
}

/**
 * DiagramOffer - Non-blocking Nano Banana Pro diagram generation
 *
 * Workflow:
 * 1. After response completes, offer diagram buttons
 * 2. User clicks Explainer or Workflow button
 * 3. Generate diagram using Nano Banana Pro (Gemini 3 Pro Image)
 * 4. Display the generated image with zoom/download controls
 * 5. If user sends new message, diagram stays visible
 */
export function DiagramOffer({
  responseContent,
  onAccept,
  onDismiss,
  className,
  autoGenerateDelay = 1500,
}: DiagramOfferProps) {
  const [isVisible, setIsVisible] = useState(false);
  const [diagramState, setDiagramState] = useState<DiagramState>({ status: "idle" });
  const [showDiagram, setShowDiagram] = useState(false);
  const [diagramType, setDiagramType] = useState<DiagramType>("explainer");
  const [zoom, setZoom] = useState(1);
  const abortControllerRef = useRef<AbortController | null>(null);

  // Show offer after delay (give user time to read)
  useEffect(() => {
    if (responseContent.length < 50) return; // Don't offer for very short responses

    const showTimer = setTimeout(() => {
      setIsVisible(true);
    }, autoGenerateDelay);

    return () => {
      clearTimeout(showTimer);
      if (abortControllerRef.current) {
        abortControllerRef.current.abort();
      }
    };
  }, [responseContent, autoGenerateDelay]);

  // Generate diagram using Nano Banana Pro
  const generateDiagram = useCallback(async (type: DiagramType) => {
    if (diagramState.status === "generating") return;

    setDiagramType(type);
    setDiagramState({ status: "generating" });
    setShowDiagram(true);

    abortControllerRef.current = new AbortController();

    try {
      const response = await fetch("/api/diagram", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          prompt: `Create a ${type} diagram based on this content`,
          context: responseContent.substring(0, 2000),
          type,
        }),
        signal: abortControllerRef.current.signal,
      });

      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.error || "Failed to generate diagram");
      }

      const result = await response.json();

      if (result.success && result.image) {
        setDiagramState({
          status: "ready",
          imageBase64: result.image.base64,
          imageMimeType: result.image.mimeType,
        });
        onAccept?.();
      } else {
        throw new Error("No image in response");
      }
    } catch (error: any) {
      if (error.name === "AbortError") {
        console.log("Diagram generation cancelled");
        setDiagramState({ status: "idle" });
      } else {
        console.error("Diagram generation failed:", error);
        setDiagramState({
          status: "error",
          error: error.message || "Unknown error",
        });
      }
    }
  }, [responseContent, diagramState.status, onAccept]);

  // Download the diagram
  const downloadDiagram = useCallback(() => {
    if (diagramState.imageBase64 && diagramState.imageMimeType) {
      const link = document.createElement("a");
      link.href = `data:${diagramState.imageMimeType};base64,${diagramState.imageBase64}`;
      link.download = `nano-banana-${diagramType}-${Date.now()}.png`;
      link.click();
    }
  }, [diagramState, diagramType]);

  // Handle dismiss
  const handleDismiss = () => {
    setIsVisible(false);
    if (abortControllerRef.current) {
      abortControllerRef.current.abort();
    }
    onDismiss?.();
  };

  // Zoom controls
  const zoomIn = () => setZoom((z) => Math.min(z + 0.25, 3));
  const zoomOut = () => setZoom((z) => Math.max(z - 0.25, 0.5));

  const typeConfig = {
    workflow: {
      icon: Workflow,
      label: "Workflow",
      color: "text-blue-400",
      bgColor: "bg-blue-500/10",
      borderColor: "border-blue-500/30",
      hoverBg: "hover:bg-blue-500/20",
    },
    explainer: {
      icon: Presentation,
      label: "Explainer",
      color: "text-amber-400",
      bgColor: "bg-amber-500/10",
      borderColor: "border-amber-500/30",
      hoverBg: "hover:bg-amber-500/20",
    },
  };

  const config = typeConfig[diagramType];
  const Icon = config.icon;

  if (!isVisible && !showDiagram) return null;

  return (
    <AnimatePresence>
      {/* Offer Buttons - shows before diagram is generated */}
      {isVisible && diagramState.status === "idle" && !showDiagram && (
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -10 }}
          className={cn(
            "flex flex-col gap-3 mt-4 p-4",
            "bg-zinc-900/50 border border-zinc-700/50 rounded-lg",
            "backdrop-blur-sm",
            className
          )}
        >
          <p className="text-sm text-zinc-400">
            Would you like me to generate a diagram?
          </p>
          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={() => generateDiagram("explainer")}
              className={cn(
                "gap-2 transition-all duration-200",
                typeConfig.explainer.bgColor,
                typeConfig.explainer.borderColor,
                typeConfig.explainer.hoverBg
              )}
            >
              <Presentation className={cn("h-4 w-4", typeConfig.explainer.color)} />
              <span className={typeConfig.explainer.color}>Explainer</span>
            </Button>

            <Button
              variant="outline"
              size="sm"
              onClick={() => generateDiagram("workflow")}
              className={cn(
                "gap-2 transition-all duration-200",
                typeConfig.workflow.bgColor,
                typeConfig.workflow.borderColor,
                typeConfig.workflow.hoverBg
              )}
            >
              <Workflow className={cn("h-4 w-4", typeConfig.workflow.color)} />
              <span className={typeConfig.workflow.color}>Workflow</span>
            </Button>

            <Button
              variant="ghost"
              size="sm"
              onClick={handleDismiss}
              className="ml-auto h-8 w-8 p-0 text-zinc-500 hover:text-zinc-300"
            >
              <X className="h-4 w-4" />
            </Button>
          </div>
          <p className="text-xs text-zinc-500">
            Powered by Nano Banana Pro (Gemini 3 Pro Image)
          </p>
        </motion.div>
      )}

      {/* Diagram Display - shows after generation starts */}
      {showDiagram && (
        <motion.div
          initial={{ opacity: 0, height: 0 }}
          animate={{ opacity: 1, height: "auto" }}
          exit={{ opacity: 0, height: 0 }}
          className={cn(
            "mt-4 rounded-lg overflow-hidden",
            "border border-purple-500/30 bg-[#1e1e2e]",
            className
          )}
        >
          {/* Header with controls */}
          <div className="flex items-center justify-between p-3 border-b border-purple-500/20 bg-zinc-900/50">
            <div className="flex items-center gap-2">
              <Icon className={cn("h-4 w-4", config.color)} />
              <span className="text-sm text-zinc-300">Nano Banana Pro</span>
              <Badge
                variant="outline"
                className={cn("text-[10px]", config.bgColor, config.borderColor, config.color)}
              >
                {config.label}
              </Badge>
              {diagramState.status === "generating" && (
                <Badge variant="outline" className="text-[10px] bg-purple-500/10 border-purple-500/30 text-purple-400">
                  Generating...
                </Badge>
              )}
              {diagramState.status === "ready" && (
                <Badge variant="outline" className="text-[10px] bg-green-500/10 border-green-500/30 text-green-400">
                  Ready
                </Badge>
              )}
            </div>
            <div className="flex items-center gap-1">
              {diagramState.status === "ready" && (
                <>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={zoomOut}
                    className="h-7 w-7 p-0 text-zinc-500 hover:text-zinc-300"
                  >
                    <ZoomOut className="h-3.5 w-3.5" />
                  </Button>
                  <span className="text-xs text-zinc-500 min-w-[2.5rem] text-center">
                    {Math.round(zoom * 100)}%
                  </span>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={zoomIn}
                    className="h-7 w-7 p-0 text-zinc-500 hover:text-zinc-300"
                  >
                    <ZoomIn className="h-3.5 w-3.5" />
                  </Button>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={downloadDiagram}
                    className="h-7 w-7 p-0 text-zinc-500 hover:text-zinc-300"
                    title="Download"
                  >
                    <Download className="h-3.5 w-3.5" />
                  </Button>
                </>
              )}
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setShowDiagram(false)}
                className="h-7 w-7 p-0 text-zinc-500 hover:text-zinc-300"
              >
                <ChevronUp className="h-3.5 w-3.5" />
              </Button>
            </div>
          </div>

          {/* Diagram content */}
          <div className="p-4 min-h-[250px] flex items-center justify-center">
            {diagramState.status === "generating" && (
              <div className="flex flex-col items-center gap-3">
                <Loader2 className="h-8 w-8 animate-spin text-purple-400" />
                <p className="text-sm text-zinc-400">
                  Creating Excalidraw-style diagram...
                </p>
              </div>
            )}

            {diagramState.status === "error" && (
              <div className="flex flex-col items-center gap-3 text-red-400">
                <p className="text-sm">Failed to generate diagram</p>
                <p className="text-xs text-zinc-500">{diagramState.error}</p>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => generateDiagram(diagramType)}
                  className="bg-zinc-800 border-zinc-700"
                >
                  Try Again
                </Button>
              </div>
            )}

            {diagramState.status === "ready" && diagramState.imageBase64 && (
              <div
                className="overflow-auto max-w-full max-h-[500px] cursor-grab active:cursor-grabbing"
                style={{ transform: `scale(${zoom})`, transformOrigin: "center" }}
              >
                <img
                  src={`data:${diagramState.imageMimeType};base64,${diagramState.imageBase64}`}
                  alt={`${diagramType} diagram`}
                  className="max-w-full h-auto rounded"
                />
              </div>
            )}
          </div>
        </motion.div>
      )}

      {/* Collapsed indicator - shows when diagram is hidden but ready */}
      {!showDiagram && diagramState.status === "ready" && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="mt-4"
        >
          <Button
            variant="outline"
            size="sm"
            onClick={() => setShowDiagram(true)}
            className={cn(
              "gap-2 transition-all duration-200",
              "bg-purple-500/10 border-purple-500/30 hover:bg-purple-500/20"
            )}
          >
            <Icon className={cn("h-4 w-4", config.color)} />
            <span className="text-purple-400">Show Diagram</span>
          </Button>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

/**
 * Hook for managing diagram offer state across the chat
 */
export function useDiagramOffer() {
  const [shouldOffer, setShouldOffer] = useState(false);
  const [lastResponseId, setLastResponseId] = useState<string | null>(null);

  const offerDiagram = useCallback((responseId: string) => {
    setLastResponseId(responseId);
    setShouldOffer(true);
  }, []);

  const dismissOffer = useCallback(() => {
    setShouldOffer(false);
  }, []);

  const cancelOffer = useCallback(() => {
    setShouldOffer(false);
    setLastResponseId(null);
  }, []);

  return {
    shouldOffer,
    lastResponseId,
    offerDiagram,
    dismissOffer,
    cancelOffer,
  };
}

export default DiagramOffer;
